### ISSUE TITLE
OAuth Error

### ISSUE THREAD

**Issue by ghost** [Nerodesk/nerodesk#87]
Error:

> App Not Setup: The developers of this app have not set up this app properly for Facebook Login.

**Comment by yegor256** [comment]
@k0r I think the problem is that it's a test application and Facebook doesn't allow you to use it. It only allows me at the moment. I have to add you to the list of "testers" in the app config panel. In order to do this, you should be in the list of my Facebook friends :) so, please send me a friend request in facebook, this is my page there: https://www.facebook.com/yegor.bugayenko

**Comment by k0r** [comment]
@yegor256 confirm?

**Comment by yegor256** [comment]
@k0r I added you to the list of "testers", but facebook says it's "pending". I suspect you should approve this operation on your end.

**Comment by ghost** [comment]
@yegor256 still receiving error.

**Comment by yegor256** [comment]
@k0r you're still in "pending" status. You should register as a developer in Facebook, as I understand and confirm your tester status in dev-nerodesk application.

**Comment by ghost** [comment]
@yegor256 works, thanks.

**Comment by karato** [comment]
@yegor256 your task, 30 mins is budget

**Comment by ghost** [comment]
@karato oauth works after adding fb accts to @yegor256 dev list.

**Comment by yegor256** [comment]
@k0r please close the ticket if the problem is fixed

**Comment by karato** [comment]
@yegor256 paid, thanks, added **30 mins** to your account, payment `000-8957e3b7`. +30 to your rating, your total score is [+8493](http://www.netbout.com/b/35008?open=rating)
